/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "text-default-default": "#1e1e1e",
        "text-default-secondary": "#757575",
        "background-default-default": "#fff",
        "border-default-default": "#d9d9d9",
        "icon-default-tertiary": "#b3b3b3",
        "background-utilities-scrim": "rgba(255, 255, 255, 0.8)",
        "text-utilities-text-on-overlay": "#0c0c0d",
        "background-neutral-tertiary": "#e3e3e3",
        "border-neutral-secondary": "#767676",
        "background-brand-default": "#2c2c2c",
        "border-brand-default": "#2c2c2c",
        "text-brand-on-brand": "#f5f5f5",
        "background-default-secondary": "#f5f5f5",
        "icon-default-default": "#1e1e1e",
        "background-brand-tertiary": "#f5f5f5",
        "text-brand-on-brand-secondary": "#1e1e1e",
        "black-200": "rgba(12, 12, 13, 0.1)",
        "black-100": "rgba(12, 12, 13, 0.05)",
        "body-strong": "#fff",
        "title-page": "#fff",
        "tkh-100": "#212633",
        "tkh-60": "#8e9abb",
        "red-test-100": "#f93535",
        limegreen: "#34c759",
        goldenrod: "#f9ab35",
        royalblue: "#356cf9",
        black: "#000",
        gray: {
          100: "rgba(0, 0, 0, 0.25)",
        },
      },
      spacing: {
        "space-200": "8px",
        "space-400": "16px",
        "space-300": "12px",
        "space-800": "32px",
        "space-600": "24px",
        "space-4000": "160px",
        "num-120": "120px",
        "num-149": "149px",
        "num-89": "89px",
        "num-236": "236px",
        "num-29": "29px",
      },
      fontFamily: {
        "body-font-family": "Inter, system-ui, sans-serif",
        "title-hero-font-family": "Inter, system-ui, sans-serif",
        "subtitle-font-family": "Inter, system-ui, sans-serif",
        "subheading-font-family": "Inter, system-ui, sans-serif",
        "heading-font-family": "Inter, system-ui, sans-serif",
        "title-page-font-family": "Inter, system-ui, sans-serif",
        "helvetica-neue": "Helvetica Neue",
        inherit: "inherit",
        "sf-pro-text": "SF Pro Text",
      },
      borderRadius: {
        "radius-200": "8px",
        "scale-06": "32px",
        "num-4": "4px",
      },
      borderWidth: {
        "stroke-border": "1px",
        "border-width": "1px",
      },
      fontSize: {
        "body-size-medium": "16px",
        "title-hero-size": "72px",
        "subtitle-size-base": "32px",
        "subheading-size-medium": "20px",
        "heading-size-base": "24px",
        "subtitle-size-small": "24px",
        "title-page-size-base": "48px",
        "body-size-small": "14px",
        "num-14": "14px",
        "num-inherit": "inherit",
      },
      fontWeight: {
        "body-font-weight-regular": "400",
        "title-hero-font-weight": "700",
        "subtitle-font-weight": "400",
        "subheading-font-weight": "400",
        "body-font-weight-strong": "600",
        "heading-font-weight": "600",
        "title-page-font-weight": "700",
      },
      letterSpacing: {
        "num--0_03": "-0.03em",
        "num--0_02": "-0.02em",
      },
    },
  },
  plugins: [],
};
